export const KEYS = {
    backspace: {key: 8, value: "Backspace", value2: ""},
    tab: {key: 9, value: "Tab", value2: ""},
    enter: {key:0, value: "Enter", value2: ""},
    shiftLeft: {key:1, value: "Shift", value2: ""},
    shiftRight: {key:2, value: "Shift", value2: ""},
    ctrlLeft: {key:3, value: "Ctrl", value2: ""},
    ctrlRight: {key:4, value: "Ctrl", value2: ""},
    altLeft: {key:5, value: "Alt", value2: ""},
    altRight: {key:6, value: "AltGr", value2: ""},
    pauseBreak: {key:7, value: "Pause Break", value2: ""},
    capsLock: {key:8, value: "Caps Lock", value2: ""}, 
    esc: {key:9, value: "Esc", value2: ""},
    space: {key:10, value: "", value2: ""},
    pageUp: {key:11, value: "Page Up", value2: ""}, 
    pageDown: {key:12, value:"Page Down", value2: ""},
    end: {key: 0, value: "End", value2: ""},
    home: {key: 0, value: "Home", value2: ""},
    leftArrow: {key: 0, value: "", value2: ""},
    upArrow: {key: 0, value: "", value2: ""},
    rightArrow: {key: 0, value: "", value2: ""},
    downArrow: {key: 0, value: "", value2: ""},
    printScreen: {key: 0, value: "Print Screen", value2: ""},
    insert: {key: 0, value: "Insert", value2: ""},
    delete: {key: 0, value: "Delete", value2: ""},
    zero: {key: 48, value: "0", value2: ")"},
    one: {key: 49, value: "1", value2: "!"},
    two: {key: 50, value: "2", value2: "@"},
    three: {key: 51, value: "3", value2: "#"},
    four: {key: 52, value: "4", value2: "$"},
    five: {key: 53, value: "5", value2: "%"},
    six: {key: 54, value: "6", value2: "^"},
    seven: {key: 55, value: "7", value2: "&"},
    eight: {key: 56, value: "8", value2: "*"},
    nine: {key: 57,value: "9", value2: "("},
    a: {key: 0, value: "A", value2: ""},
    b: {key: 0, value: "B", value2: ""},
    c: {key: 0, value: "C", value2: ""},
    d: {key: 0, value: "D", value2: ""},
    e: {key: 0, value: "E", value2: ""},
    f: {key: 0, value: "F", value2: ""},
    g: {key: 0, value: "G", value2: ""},
    h: {key: 0, value: "H", value2: ""},
    i: {key: 0, value: "I", value2: ""},
    j: {key: 0, value: "J", value2: ""},
    k: {key: 0, value: "K", value2: ""},
    l: {key: 0, value: "L", value2: ""},
    m: {key: 0, value: "M", value2: ""},
    n: {key: 0, value: "N", value2: ""},
    o: {key: 0, value: "O", value2: ""},
    p: {key: 0, value: "P", value2: ""},
    q: {key: 0, value: "Q", value2: ""},
    r: {key: 0, value: "R", value2: ""},
    s: {key: 0, value: "S", value2: ""},
    t: {key: 0, value: "T", value2: ""},
    u: {key: 0, value: "U", value2: ""},
    v: {key: 0, value: "V", value2: ""},
    w: {key: 0, value: "W", value2: ""},
    x: {key: 0, value: "X", value2: ""},
    y: {key: 0, value: "Y", value2: ""},
    z: {key: 0, value: "Z", value2: ""},
    cmdLeft: {key: 0, value:"cmd", value2: ""},
    cmdRight: {key: 0, value:"cmd", value2: ""},
    select: {key: 0, value:"select", value2: ""},
    numZero:{key: 0, value:"0", value2: "Insert"},
    numOne:{key: 0, value:"1", value2: "End"},
    numTwo:{key: 0, value:"2", value2: "Down Arrow"},
    numThree:{key: 0, value:"3", value2: "PgDn"},
    numFour:{key: 0, value:"4", value2: "Left Arrow"},
    numFive:{key: 0, value:"5", value2: ""},
    numSix:{key: 0, value:"6", value2: "Right Arrow"},
    numSeven:{key: 0, value:"7", value2: "Home"},
    numEight:{key: 0, value:"8", value2: "Up Arrow"},
    numNine:{key: 0, value:"9", value2: "PgUp"},
    multiply:{key: 0, value:"*", value2: ""},
    add:{key: 0, value:"+", value2: ""},
    subtract:{key: 0, value:"-", value2: ""},
    dot:{key: 0, value:".", value2: ""},
    divide:{key: 0, value:"/", value2: ""},
    f1:{key: 112, value:"F1", value2: ""},
    f2:{key: 113, value:"F2", value2: ""},
    f3:{key: 114, value:"F3", value2: ""},
    f4:{key: 115, value:"F4", value2: ""},
    f5:{key: 116, value:"F5", value2: ""},
    f6:{key: 117, value:"F6", value2: ""},
    f7:{key: 118, value:"F7", value2: ""},
    f8:{key: 119, value:"F8", value2: ""},
    f9:{key: 120, value:"F9", value2: ""},
    f10:{key: 121, value:"F10", value2: ""},
    f11:{key: 122, value:"F11", value2: ""},
    f12:{key: 123, value:"F12", value2: ""},
    numLock:{key: 0, value:"Num Lock", value2: ""},
    scrollLock:{key: 0, value:"Scroll Lock", value2: ""},
    semicolon:{key: 0, value:";", value2: ":"},
    equal:{key: 187, value:"=", value2: "+"},
    comma:{key: 0, value:",", value2: "<"},
    dash:{key: 189, value:"-", value2: "_"},
    period:{key: 0, value:".", value2: ">"},
    forwardSlash:{key: 0, value:"/", value2: "?"},
    backQuote:{key: 0, value:"`", value2: "~"},
    openBracket:{key: 0, value:"[", value2: "{"},
    backSlash:{key: 0, value:"\\", value2: "|"},
    closeBracket:{key: 0, value:"]", value2: "}"},
    singleQuote:{key: 0, value:"'", value2: "\""},
}
export const FUNCTIONS = ["esc", "f1","f2","f3","f4","f5","f6", "f7", "f8", "f9", "f10", "f11", "f12"]
export const NUM = ["backQuote", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "zero", "dash", "equal", "backspace"]
export const TAB_ROW = ["tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "openBracket", "closeBracket", "backSlash"]
export const CAPS_ROW = ["capsLock", "a", "s", "d", "f", "g", "h", "j", "k", "l", "semicolon", "singleQuote", "enter"]
export const SHIFT_ROW = ["shiftLeft","z","x","c","v","b","n","m","comma","period","forwardSlash","shiftRight"]
export const CTRL_ROW = ["ctrlLeft","cmdLeft","altLeft","space","altRight","cmdRight","ctrlRight"]