export const KEYS = {
    backspace: {key: 8, value: "Backspace", value2: ""},
    tab: {key: 9, value: "Tab", value2: ""},
    enter: {key:13, value: "Enter", value2: ""},
    shiftLeft: {key:16, value: "Shift", value2: ""},
    shiftRight: {key:16, value: "Shift", value2: ""},
    ctrlLeft: {key:17, value: "Ctrl", value2: ""},
    ctrlRight: {key:17, value: "Ctrl", value2: ""},
    altLeft: {key:18, value: "Alt", value2: ""},
    altRight: {key:18, value: "AltGr", value2: ""},
    pauseBreak: {key:19, value: "Pause Break", value2: ""},
    capsLock: {key:20, value: "Caps Lock", value2: ""}, 
    esc: {key:27, value: "Esc", value2: ""},
    space: {key:32, value: "", value2: ""},
    pageUp: {key:33, value: "Page Up", value2: ""}, 
    pageDown: {key:34, value:"Page Down", value2: ""},
    end: {key: 35, value: "End", value2: ""},
    home: {key: 36, value: "Home", value2: ""},
    leftArrow: {key: 37, value: "\u2190", value2: ""},
    upArrow: {key: 38, value: "\u2191", value2: ""},
    rightArrow: {key: 39, value: "\u2192", value2: ""},
    downArrow: {key: 40, value: "\u2193", value2: ""},
    printScreen: {key: 44, value: "Print Screen", value2: ""},
    insert: {key: 45, value: "Insert", value2: ""},
    delete: {key: 46, value: "Delete", value2: ""},
    zero: {key: 48, value: "0", value2: ")"},
    one: {key: 49, value: "1", value2: "!"},
    two: {key: 50, value: "2", value2: "@"},
    three: {key: 51, value: "3", value2: "#"},
    four: {key: 52, value: "4", value2: "$"},
    five: {key: 53, value: "5", value2: "%"},
    six: {key: 54, value: "6", value2: "^"},
    seven: {key: 55, value: "7", value2: "&"},
    eight: {key: 56, value: "8", value2: "*"},
    nine: {key: 57,value: "9", value2: "("},
    a: {key: 65, value: "A", value2: ""},
    b: {key: 66, value: "B", value2: ""},
    c: {key: 67, value: "C", value2: ""},
    d: {key: 68, value: "D", value2: ""},
    e: {key: 69, value: "E", value2: ""},
    f: {key: 70, value: "F", value2: ""},
    g: {key: 71, value: "G", value2: ""},
    h: {key: 72, value: "H", value2: ""},
    i: {key: 73, value: "I", value2: ""},
    j: {key: 74, value: "J", value2: ""},
    k: {key: 75, value: "K", value2: ""},
    l: {key: 76, value: "L", value2: ""},
    m: {key: 77, value: "M", value2: ""},
    n: {key: 78, value: "N", value2: ""},
    o: {key: 79, value: "O", value2: ""},
    p: {key: 80, value: "P", value2: ""},
    q: {key: 81, value: "Q", value2: ""},
    r: {key: 82, value: "R", value2: ""},
    s: {key: 83, value: "S", value2: ""},
    t: {key: 84, value: "T", value2: ""},
    u: {key: 85, value: "U", value2: ""},
    v: {key: 86, value: "V", value2: ""},
    w: {key: 87, value: "W", value2: ""},
    x: {key: 88, value: "X", value2: ""},
    y: {key: 89, value: "Y", value2: ""},
    z: {key: 90, value: "Z", value2: ""},
    cmdLeft: {key: 91, value:"cmd", value2: ""},
    cmdRight: {key: 92, value:"cmd", value2: ""},
    select: {key: 93, value:"select", value2: ""},
    numZero:{key: 96, value:"0", value2: ""},
    numOne:{key: 97, value:"1", value2: ""},
    numTwo:{key: 98, value:"2", value2: ""},
    numThree:{key: 99, value:"3", value2: ""},
    numFour:{key: 100, value:"4", value2: ""},
    numFive:{key: 101, value:"5", value2: ""},
    numSix:{key: 102, value:"6", value2: ""},
    numSeven:{key: 103, value:"7", value2: ""},
    numEight:{key: 104, value:"8", value2: ""},
    numNine:{key: 105, value:"9", value2: ""},
    multiply:{key: 106, value:"*", value2: ""},
    add:{key: 107, value:"+", value2: ""},
    subtract:{key: 109, value:"-", value2: ""},
    dot:{key: 110, value:".", value2: ""},
    divide:{key: 111, value:"/", value2: ""},
    numEnter:{key: 13, value:"Enter", value2: ""},
    f1:{key: 112, value:"F1", value2: ""},
    f2:{key: 113, value:"F2", value2: ""},
    f3:{key: 114, value:"F3", value2: ""},
    f4:{key: 115, value:"F4", value2: ""},
    f5:{key: 116, value:"F5", value2: ""},
    f6:{key: 117, value:"F6", value2: ""},
    f7:{key: 118, value:"F7", value2: ""},
    f8:{key: 119, value:"F8", value2: ""},
    f9:{key: 120, value:"F9", value2: ""},
    f10:{key: 121, value:"F10", value2: ""},
    f11:{key: 122, value:"F11", value2: ""},
    f12:{key: 123, value:"F12", value2: ""},
    numLock:{key: 144, value:"Num Lock", value2: ""},
    scrollLock:{key: 145, value:"Scroll Lock", value2: ""},
    semicolon:{key: 186, value:";", value2: ":"},
    equal:{key: 187, value:"=", value2: "+"},
    comma:{key: 188, value:",", value2: "<"},
    dash:{key: 189, value:"-", value2: "_"},
    period:{key: 190, value:".", value2: ">"},
    forwardSlash:{key: 191, value:"/", value2: "?"},
    backQuote:{key: 192, value:"`", value2: "~"},
    openBracket:{key: 219, value:"[", value2: "{"},
    backSlash:{key: 220, value:"\\", value2: "|"},
    closeBracket:{key: 221, value:"]", value2: "}"},
    singleQuote:{key: 222, value:"'", value2: "\""},
}
export const FUNCTIONS = ["esc", "f1","f2","f3","f4","f5","f6", "f7", "f8", "f9", "f10", "f11", "f12"]
export const NUM = ["backQuote", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "zero", "dash", "equal", "backspace"]
export const TAB_ROW = ["tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "openBracket", "closeBracket", "backSlash"]
export const CAPS_ROW = ["capsLock", "a", "s", "d", "f", "g", "h", "j", "k", "l", "semicolon", "singleQuote", "enter"]
export const SHIFT_ROW = ["shiftLeft","z","x","c","v","b","n","m","comma","period","forwardSlash","shiftRight"]
export const CTRL_ROW = ["ctrlLeft","cmdLeft","altLeft","space","altRight","cmdRight","ctrlRight"]
export const ARROWS_1 = ["upArrow"]
export const ARROWS_2 = ["leftArrow","downArrow","rightArrow"]
export const PRINT_ROW = ["printScreen", "scrollLock", "pauseBreak"]
export const INSERT_ROW = ["insert", "home", "pageUp"]
export const DELETE_ROW = ["delete", "end", "pageDown"]
export const NUM_LOCK_ROW = ["numLock", "divide", "multiply", "subtract"]
export const NUM_ROW_1 = ["numSeven","numEight","numNine","add"]
export const NUM_ROW_2 = ["numFour","numFive","numSix"]
export const NUM_ROW_3 = ["numOne","numTwo","numThree", "numEnter"]
export const NUM_ROW_4 = ["numZero","dot"]